# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 38f248c8663f4bd53012ff11b849a05ba567f2873377b3705208940ea1348095b1d1a61614d9e17ba27a843d37be3ecd63e6df6df47b7f18f1becaaedb0a3fb4

test:
  secret_key_base: 57af86b11016808f05cd717227cdd2a578b594ce0d77002cb5bf3abea5be73af7a5d5b4f3adf404caf4e7d543644149268ca3f78f56ce693a98311d192d8e5ff

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
